name: Battlegrounds
main: com.matsg.battlegrounds.BattlegroundsPlugin
version: 1.0.0 Beta
author: Mats9799
commands:
  battlegrounds:
    aliases: [b, bg, battleground]
    description: Main command
    usage: /battlegrounds
  loadout:
    aliases: loadoutcreator
    description: Opens the loadout manager
    usage: /loadout