name: Battlegrounds
main: com.matsg.battlegrounds.BattlegroundsPlugin
version: 1.0.0
author: Mats9799
commands:
  battlegrounds:
    aliases: [b, bg, battleground]
    description: Main command
    usage: /battlegrounds
  class:
    aliases: classcreator
    description: Opens the class manager
    usage: /class