name: Battlegrounds
main: com.matsg.battlegrounds.BattlegroundsPlugin
version: 1.1.0
author: Mats9799
commands:
  battlegrounds:
    aliases: [b, bg, battleground]
    description: Main command
    usage: /battlegrounds
  loadout:
    aliases: loadoutcreator
    description: Opens the loadout creation manager
    usage: /loadout
softdepend: [Multiverse-Core, MultiWorld]